//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace WebApplication7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lecture
    {
        public int ID { get; set; }
        public int ModuleID { get; set; }
        [Required(ErrorMessage = "Lecture title is required.")]
        public string LectureTitle { get; set; }
        [Required(ErrorMessage = "Lecture activity is required.")]
        public string LectureActivity { get; set; }
    
        public virtual Module Module { get; set; }
    }
}
