//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace WebApplication7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentModule
    {
        public int ConnectionID { get; set; }
        public int StudentID { get; set; }
        [Required(ErrorMessage = "Module is required.")]
        public int ModuleID { get; set; }
        public int LecturerID { get; set; }
        
        public virtual Module Module { get; set; }
        public virtual User User { get; set; }
    }
}
